import { parseSqlDdl } from './sql_parser.utils.ts';

/**
 * Converts SQL DDL schema to Prisma schema format.
 */
export function convertSqlToPrisma(sql: string): string {
  const schema = parseSqlDdl(sql);
  if (schema.tables.length === 0) {
    return '// No valid SQL tables found to convert to Prisma schema';
  }

  let prisma = `// Prisma Schema generated by DevSuite.dev\n\ndatasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n}\n\ngenerator client {\n  provider = "prisma-client-js"\n}\n\n`;

  for (const table of schema.tables) {
    const modelName = capitalize(table.name);
    prisma += `model ${modelName} {\n`;

    for (const col of table.columns) {
      let prismaType = 'String';
      const colUpper = col.type.toUpperCase();

      if (colUpper.includes('INT') || colUpper.includes('SERIAL')) {
        prismaType = 'Int';
      } else if (colUpper.includes('BOOL')) {
        prismaType = 'Boolean';
      } else if (colUpper.includes('TIME') || colUpper.includes('DATE')) {
        prismaType = 'DateTime';
      } else if (colUpper.includes('FLOAT') || colUpper.includes('DOUBLE') || colUpper.includes('DECIMAL')) {
        prismaType = 'Float';
      } else if (colUpper.includes('JSON')) {
        prismaType = 'Json';
      }

      const isOptional = col.isNullable ? '?' : '';
      let attributes = '';

      if (col.isPrimary) {
        attributes += ' @id';
        if (prismaType === 'String' && colUpper.includes('UUID')) {
          attributes += ' @default(uuid())';
        } else if (prismaType === 'Int') {
          attributes += ' @default(autoincrement())';
        }
      }

      if (col.name.toLowerCase() === 'created_at' && prismaType === 'DateTime') {
        attributes += ' @default(now())';
      } else if (col.name.toLowerCase() === 'updated_at' && prismaType === 'DateTime') {
        attributes += ' @updatedAt';
      }

      prisma += `  ${col.name.padEnd(16)} ${prismaType}${isOptional}${attributes}\n`;
    }

    prisma += `\n  @@map("${table.name}")\n}\n\n`;
  }

  return prisma.trim();
}

/**
 * Converts SQL DDL schema to Drizzle ORM format.
 */
export function convertSqlToDrizzle(sql: string): string {
  const schema = parseSqlDdl(sql);
  if (schema.tables.length === 0) {
    return '// No valid SQL tables found';
  }

  let drizzle = `import { pgTable, text, varchar, integer, boolean, timestamp, uuid } from 'drizzle-orm/pg-core';\n\n`;

  for (const table of schema.tables) {
    drizzle += `export const ${table.name} = pgTable('${table.name}', {\n`;

    for (const col of table.columns) {
      const colUpper = col.type.toUpperCase();
      let drizzleFunc = "text";

      if (colUpper.includes('UUID')) {
        drizzleFunc = "uuid";
      } else if (colUpper.includes('INT') || colUpper.includes('SERIAL')) {
        drizzleFunc = "integer";
      } else if (colUpper.includes('BOOL')) {
        drizzleFunc = "boolean";
      } else if (colUpper.includes('TIME') || colUpper.includes('DATE')) {
        drizzleFunc = "timestamp";
      } else if (colUpper.includes('VARCHAR')) {
        drizzleFunc = "varchar";
      }

      let chained = `${drizzleFunc}('${col.name}')`;
      if (col.isPrimary) chained += '.primaryKey()';
      if (!col.isNullable && !col.isPrimary) chained += '.notNull()';

      drizzle += `  ${col.name}: ${chained},\n`;
    }

    drizzle += `});\n\n`;
  }

  return drizzle.trim();
}

/**
 * Converts Prisma Schema models into SQL DDL CREATE TABLE statements.
 */
export function convertPrismaToSql(prisma: string): string {
  const modelRegex = /model\s+(\w+)\s*\{([\s\S]*?)\}/g;
  let match: RegExpExecArray | null;
  const ddlStatements: string[] = [];

  while ((match = modelRegex.exec(prisma)) !== null) {
    const modelName = match[1];
    const body = match[2];

    let tableName = modelName.toLowerCase();
    const mapMatch = body.match(/@@map\("([^"]+)"\)/);
    if (mapMatch) tableName = mapMatch[1];

    const lines = body.split('\n');
    const cols: string[] = [];

    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('//') || trimmed.startsWith('@@')) continue;

      const parts = trimmed.split(/\s+/);
      if (parts.length < 2) continue;

      const colName = parts[0];
      const rawType = parts[1];
      const rest = parts.slice(2).join(' ');

      const isOptional = rawType.endsWith('?');
      const cleanType = rawType.replace('?', '');

      let sqlType = 'VARCHAR(255)';
      if (cleanType === 'Int') sqlType = 'INTEGER';
      else if (cleanType === 'Boolean') sqlType = 'BOOLEAN';
      else if (cleanType === 'DateTime') sqlType = 'TIMESTAMP';
      else if (cleanType === 'Float') sqlType = 'DECIMAL(10, 2)';
      else if (cleanType === 'Json') sqlType = 'JSONB';
      else if (cleanType === 'String' && rest.includes('@id')) sqlType = 'UUID';

      let constraints = '';
      if (rest.includes('@id')) constraints += ' PRIMARY KEY';
      if (!isOptional && !rest.includes('@id')) constraints += ' NOT NULL';
      if (rest.includes('@unique')) constraints += ' UNIQUE';

      cols.push(`  ${colName} ${sqlType}${constraints}`);
    }

    if (cols.length > 0) {
      ddlStatements.push(`CREATE TABLE ${tableName} (\n${cols.join(',\n')}\n);`);
    }
  }

  return ddlStatements.join('\n\n') || '-- No Prisma models found';
}

function capitalize(str: string): string {
  if (!str) return str;
  return str.charAt(0).toUpperCase() + str.slice(1);
}
